#!/usr/bin/env python3
"""Deterministically build the ``miniproject`` test fixture.

The fixture is a real git repository (a small task-tracker called *taskhub*
with a Python backend and a TypeScript frontend) used by the test suite and
the eval gold set. It is generated by this script rather than committed as a
tarball so it stays reviewable and reproducible (see DECISIONS.md).

Determinism: fixed author/committer identity and timestamps, fixed branch
name (``main``), fixed file contents. Building twice yields byte-identical
history (same commit SHAs).

Usage::

    python tests/fixtures/build_miniproject.py [dest]   # default: ./miniproject
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

FIXTURE_DIRNAME = "miniproject"

# Bump whenever COMMITS change so prebuilt fixtures rebuild (conftest checks
# the marker written into the built repo's .git dir).
FIXTURE_VERSION = 3
_VERSION_MARKER = "sherpa-fixture-version"

_AUTHOR_NAME = "Fixture Bot"
_AUTHOR_EMAIL = "fixture@example.com"
_BASE_DATE = "2024-01-{day:02d}T12:00:00+00:00"

# --------------------------------------------------------------------------
# File contents, grouped by commit. Paths are repo-relative. A value of None
# means "delete this path in this commit".
# --------------------------------------------------------------------------

_COMMIT_1_PY_CORE: dict[str, str | None] = {
    "README.md": "# taskhub\n\nA tiny task tracker used as a sherpa test fixture.\n",
    "pyserver/__init__.py": '"""taskhub server package."""\n',
    "pyserver/config.py": '''\
"""Application configuration loading."""

import json
import os
from dataclasses import dataclass


@dataclass
class Settings:
    """Runtime settings for the taskhub server."""

    database_path: str = "taskhub.db"
    host: str = "127.0.0.1"
    port: int = 8080
    debug: bool = False
    webhook_url: str = ""


def load_config(path: str | None = None) -> Settings:
    """Load settings from a JSON file, environment, or defaults.

    Precedence: explicit file > TASKHUB_CONFIG env var > built-in defaults.
    """
    candidate = path or os.environ.get("TASKHUB_CONFIG")
    if candidate and os.path.exists(candidate):
        with open(candidate, "r", encoding="utf-8") as fh:
            raw = json.load(fh)
        return Settings(**raw)
    return Settings()
''',
    "pyserver/db.py": '''\
"""SQLite database access layer."""

import sqlite3

_SCHEMA = """
CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    owner_id INTEGER,
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL
);
"""


class Database:
    """Thin wrapper around sqlite3 with row factories."""

    def __init__(self, path: str) -> None:
        self.path = path
        self._conn: sqlite3.Connection | None = None

    def connect(self) -> sqlite3.Connection:
        """Open (and memoize) the database connection, creating the schema."""
        if self._conn is None:
            self._conn = sqlite3.connect(self.path)
            self._conn.row_factory = sqlite3.Row
            self._conn.executescript(_SCHEMA)
        return self._conn

    def execute(self, sql: str, params: tuple = ()) -> sqlite3.Cursor:
        return self.connect().execute(sql, params)

    def fetch_all(self, sql: str, params: tuple = ()) -> list[sqlite3.Row]:
        return self.execute(sql, params).fetchall()

    def close(self) -> None:
        if self._conn is not None:
            self._conn.close()
            self._conn = None
''',
    "pyserver/models/__init__.py": '"""Data models."""\n',
    "pyserver/models/task.py": '''\
"""Task model."""

from dataclasses import dataclass
from enum import Enum


class TaskStatus(str, Enum):
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    DONE = "done"


@dataclass
class Task:
    id: int
    title: str
    status: TaskStatus
    owner_id: int | None
    created_at: str


def task_from_row(row) -> Task:
    """Build a Task from a sqlite3.Row."""
    return Task(
        id=row["id"],
        title=row["title"],
        status=TaskStatus(row["status"]),
        owner_id=row["owner_id"],
        created_at=row["created_at"],
    )
''',
    "pyserver/models/user.py": '''\
"""User model."""

from dataclasses import dataclass


@dataclass
class User:
    id: int
    email: str
    name: str


def user_from_row(row) -> User:
    """Build a User from a sqlite3.Row."""
    return User(id=row["id"], email=row["email"], name=row["name"])
''',
    "pyserver/utils/__init__.py": '"""Shared utilities."""\n',
    "pyserver/utils/text.py": '''\
"""Text helpers."""

import re

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(title: str) -> str:
    """Convert a task title into a url-safe slug.

    "Fix login bug!" -> "fix-login-bug"
    """
    slug = _SLUG_RE.sub("-", title.lower()).strip("-")
    return slug or "untitled"


def truncate(text: str, limit: int = 80) -> str:
    """Truncate text to ``limit`` characters, appending an ellipsis."""
    if len(text) <= limit:
        return text
    return text[: limit - 1] + "\\u2026"
''',
    "pyserver/utils/time.py": '''\
"""Time helpers."""

from datetime import datetime, timezone


def utc_now_iso() -> str:
    """Current UTC time as an ISO-8601 string."""
    return datetime.now(timezone.utc).isoformat()


def parse_iso(value: str) -> datetime:
    """Parse an ISO-8601 string into an aware datetime."""
    dt = datetime.fromisoformat(value)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt


def humanize_delta(seconds: float) -> str:
    """Render a duration in seconds as a short human string like '3h' or '2d'."""
    if seconds < 60:
        return f"{int(seconds)}s"
    if seconds < 3600:
        return f"{int(seconds // 60)}m"
    if seconds < 86400:
        return f"{int(seconds // 3600)}h"
    return f"{int(seconds // 86400)}d"
''',
    "pyserver/validators.py": '''\
"""Input validation for API payloads."""

import re

_EMAIL_RE = re.compile(r"^[A-Za-z0-9._-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")

MAX_TITLE_LENGTH = 200


def validate_title(title: str) -> str:
    """Validate a task title; returns the stripped title or raises ValueError."""
    cleaned = title.strip()
    if not cleaned:
        raise ValueError("title must not be empty")
    if len(cleaned) > MAX_TITLE_LENGTH:
        raise ValueError(f"title longer than {MAX_TITLE_LENGTH} characters")
    return cleaned


def validate_email(email: str) -> str:
    """Validate an email address; returns it lowercased or raises ValueError."""
    cleaned = email.strip().lower()
    if not _EMAIL_RE.match(cleaned):
        raise ValueError(f"invalid email: {email!r}")
    return cleaned
''',
    "pyserver/legacy.py": '''\
"""Deprecated one-shot sync kept for reference. Do not use."""

from pyserver.db import Database


def old_sync_tasks(db: Database) -> int:
    """Legacy full-table rewrite sync. Superseded by incremental routes."""
    rows = db.fetch_all("SELECT * FROM tasks")
    count = 0
    for row in rows:
        db.execute(
            "UPDATE tasks SET status = ? WHERE id = ?",
            (row["status"], row["id"]),
        )
        count += 1
    return count
''',
    "pyserver/routes/__init__.py": '''\
"""HTTP route registration."""

from pyserver.routes import tasks, users


def register_routes(app) -> None:
    """Attach all route handlers to the app's dispatch table."""
    app.route("GET", "/tasks", tasks.list_tasks)
    app.route("POST", "/tasks", tasks.create_task)
    app.route("POST", "/tasks/complete", tasks.complete_task)
    app.route("GET", "/users", users.get_user)
    app.route("POST", "/users", users.create_user)
''',
    "pyserver/routes/tasks.py": '''\
"""Task routes."""

from pyserver.db import Database
from pyserver.models.task import TaskStatus, task_from_row
from pyserver.utils.time import utc_now_iso
from pyserver.validators import validate_title


def list_tasks(db: Database, params: dict) -> list[dict]:
    """Return all tasks, optionally filtered by status."""
    status = params.get("status")
    if status:
        rows = db.fetch_all("SELECT * FROM tasks WHERE status = ?", (status,))
    else:
        rows = db.fetch_all("SELECT * FROM tasks")
    return [task_from_row(row).__dict__ for row in rows]


def create_task(db: Database, payload: dict) -> dict:
    """Create a new task from a JSON payload."""
    title = validate_title(payload["title"])
    cursor = db.execute(
        "INSERT INTO tasks (title, status, owner_id, created_at) VALUES (?, ?, ?, ?)",
        (title, TaskStatus.OPEN.value, payload.get("owner_id"), utc_now_iso()),
    )
    return {"id": cursor.lastrowid, "title": title}


def complete_task(db: Database, payload: dict) -> dict:
    """Mark a task as done."""
    task_id = payload["task_id"]
    db.execute(
        "UPDATE tasks SET status = ? WHERE id = ?",
        (TaskStatus.DONE.value, task_id),
    )
    return {"id": task_id, "status": TaskStatus.DONE.value}
''',
    "pyserver/routes/users.py": '''\
"""User routes."""

from pyserver.db import Database
from pyserver.models.user import user_from_row
from pyserver.validators import validate_email


def get_user(db: Database, params: dict) -> dict:
    """Fetch one user by id."""
    row_list = db.fetch_all("SELECT * FROM users WHERE id = ?", (params["id"],))
    if not row_list:
        raise KeyError(f"no such user: {params['id']}")
    return user_from_row(row_list[0]).__dict__


def create_user(db: Database, payload: dict) -> dict:
    """Create a user after validating the email address."""
    email = validate_email(payload["email"])
    cursor = db.execute(
        "INSERT INTO users (email, name) VALUES (?, ?)",
        (email, payload.get("name", "")),
    )
    return {"id": cursor.lastrowid, "email": email}
''',
    "pyserver/app.py": '''\
"""Application wiring and entry point."""

from pyserver.config import Settings, load_config
from pyserver.db import Database
from pyserver.routes import register_routes


class App:
    """Minimal dispatch-table web app (framework-free for the fixture)."""

    def __init__(self, settings: Settings) -> None:
        self.settings = settings
        self.db = Database(settings.database_path)
        self._routes: dict[tuple[str, str], object] = {}

    def route(self, method: str, path: str, handler) -> None:
        self._routes[(method, path)] = handler

    def dispatch(self, method: str, path: str, payload: dict) -> object:
        handler = self._routes[(method, path)]
        return handler(self.db, payload)


def create_app(config_path: str | None = None) -> App:
    """Build the app: load config, connect the database, register routes."""
    settings = load_config(config_path)
    app = App(settings)
    app.db.connect()
    register_routes(app)
    return app


def run() -> None:
    """Start the server (fixture stub: builds the app and reports readiness)."""
    app = create_app()
    print(f"taskhub listening on {app.settings.host}:{app.settings.port}")
''',
}

_COMMIT_2_TS_FRONTEND: dict[str, str | None] = {
    "webclient/package.json": '{\n  "name": "taskhub-webclient",\n  "version": "0.1.0",\n  "private": true\n}\n',
    "webclient/src/types.ts": """\
/** Shared API types. */

export type TaskStatus = 'open' | 'in_progress' | 'done';

export interface Task {
  id: number;
  title: string;
  status: TaskStatus;
  ownerId: number | null;
  createdAt: string;
}

export interface User {
  id: number;
  email: string;
  name: string;
}
""",
    "webclient/src/http.ts": """\
/** Low-level HTTP helpers. */

export class HttpError extends Error {
  constructor(public status: number, message: string) {
    super(message);
    this.name = 'HttpError';
  }
}

export async function request<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, init);
  if (!response.ok) {
    throw new HttpError(response.status, `request failed: ${response.status} ${url}`);
  }
  return (await response.json()) as T;
}
""",
    "webclient/src/api.ts": """\
/** Typed API client for the taskhub server. */

import { request } from './http';
import type { Task, User } from './types';

const BASE = '/api';

export async function fetchTasks(status?: string): Promise<Task[]> {
  const query = status ? `?status=${encodeURIComponent(status)}` : '';
  return request<Task[]>(`${BASE}/tasks${query}`);
}

export async function createTask(title: string, ownerId?: number): Promise<Task> {
  return request<Task>(`${BASE}/tasks`, {
    method: 'POST',
    body: JSON.stringify({ title, owner_id: ownerId }),
  });
}

export async function fetchUser(id: number): Promise<User> {
  return request<User>(`${BASE}/users?id=${id}`);
}
""",
    "webclient/src/auth.ts": """\
/** Client-side auth: token storage and login. */

import { request } from './http';

const TOKEN_KEY = 'taskhub.token';

export function storeToken(token: string): void {
  window.localStorage.setItem(TOKEN_KEY, token);
}

export function getToken(): string | null {
  return window.localStorage.getItem(TOKEN_KEY);
}

export async function login(email: string, password: string): Promise<void> {
  const result = await request<{ token: string }>('/api/login', {
    method: 'POST',
    body: JSON.stringify({ email, password }),
  });
  storeToken(result.token);
}
""",
    "webclient/src/store.ts": """\
/** In-memory task store with change subscription. */

import { createTask, fetchTasks } from './api';
import type { Task } from './types';

type Listener = (tasks: Task[]) => void;

export class TaskStore {
  private tasks: Task[] = [];
  private listeners: Listener[] = [];

  subscribe(listener: Listener): () => void {
    this.listeners.push(listener);
    return () => {
      this.listeners = this.listeners.filter((l) => l !== listener);
    };
  }

  async refresh(status?: string): Promise<void> {
    this.tasks = await fetchTasks(status);
    this.emit();
  }

  async add(title: string): Promise<void> {
    const task = await createTask(title);
    this.tasks = [...this.tasks, task];
    this.emit();
  }

  all(): Task[] {
    return this.tasks;
  }

  private emit(): void {
    for (const listener of this.listeners) {
      listener(this.tasks);
    }
  }
}
""",
    "webclient/src/utils/format.ts": """\
/** Text formatting helpers. */

export function formatTitle(title: string, limit = 60): string {
  const trimmed = title.trim();
  if (trimmed.length <= limit) {
    return trimmed;
  }
  return `${trimmed.slice(0, limit - 1)}\\u2026`;
}

export function pluralize(count: number, singular: string, plural?: string): string {
  const word = count === 1 ? singular : plural ?? `${singular}s`;
  return `${count} ${word}`;
}
""",
    "webclient/src/utils/dates.ts": """\
/** Date helpers for the UI. */

export function parseDate(iso: string): Date {
  return new Date(iso);
}

export function formatRelative(iso: string, now: Date = new Date()): string {
  const then = parseDate(iso);
  const seconds = Math.max(0, (now.getTime() - then.getTime()) / 1000);
  if (seconds < 60) return 'just now';
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
  return `${Math.floor(seconds / 86400)}d ago`;
}
""",
    "webclient/src/components/TaskItem.tsx": """\
/** A single task row. */

import { formatTitle } from '../utils/format';
import type { Task } from '../types';

export interface TaskItemProps {
  task: Task;
  onComplete: (id: number) => void;
}

export function TaskItem({ task, onComplete }: TaskItemProps) {
  return (
    <li className={`task task--${task.status}`}>
      <span className="task__title">{formatTitle(task.title)}</span>
      <button onClick={() => onComplete(task.id)} disabled={task.status === 'done'}>
        done
      </button>
    </li>
  );
}
""",
    "webclient/src/components/UserBadge.tsx": """\
/** Compact user chip with a relative "joined" date. */

import { formatRelative } from '../utils/dates';
import type { User } from '../types';

export interface UserBadgeProps {
  user: User;
  joinedAt: string;
}

export function UserBadge({ user, joinedAt }: UserBadgeProps) {
  return (
    <span className="user-badge" title={user.email}>
      {user.name} · joined {formatRelative(joinedAt)}
    </span>
  );
}
""",
    "webclient/src/components/TaskList.tsx": """\
/** Task list bound to the TaskStore. */

import { TaskStore } from '../store';
import { TaskItem } from './TaskItem';
import { pluralize } from '../utils/format';
import type { Task } from '../types';

export interface TaskListProps {
  store: TaskStore;
  tasks: Task[];
}

export function TaskList({ store, tasks }: TaskListProps) {
  const onComplete = (id: number) => {
    void store.refresh();
    console.info(`completing task ${id}`);
  };
  return (
    <div>
      <p>{pluralize(tasks.length, 'task')}</p>
      <ul>
        {tasks.map((task) => (
          <TaskItem key={task.id} task={task} onComplete={onComplete} />
        ))}
      </ul>
    </div>
  );
}
""",
    "webclient/src/index.ts": """\
/** App bootstrap. */

import { TaskStore } from './store';
import { getToken } from './auth';

export async function bootstrap(): Promise<TaskStore> {
  const store = new TaskStore();
  if (getToken() !== null) {
    await store.refresh();
  }
  return store;
}
""",
}

_COMMIT_3_RETRY: dict[str, str | None] = {
    "pyserver/http_client.py": '''\
"""Outbound HTTP client with retry logic."""

import json
import time
import urllib.error
import urllib.request

DEFAULT_ATTEMPTS = 3
BACKOFF_BASE_SECONDS = 0.5


class HttpClient:
    """Small stdlib-based HTTP client with exponential-backoff retries."""

    def __init__(self, attempts: int = DEFAULT_ATTEMPTS, backoff: float = BACKOFF_BASE_SECONDS) -> None:
        self.attempts = attempts
        self.backoff = backoff

    def retry_request(self, url: str, data: bytes | None = None, method: str = "GET") -> bytes:
        """Perform an HTTP request, retrying transient failures.

        Retries up to ``self.attempts`` times with exponential backoff
        (0.5s, 1s, 2s, ...). Raises the last error if all attempts fail.
        """
        last_error: Exception | None = None
        for attempt in range(self.attempts):
            try:
                req = urllib.request.Request(url, data=data, method=method)
                with urllib.request.urlopen(req, timeout=10) as resp:
                    return resp.read()
            except (urllib.error.URLError, TimeoutError) as exc:
                last_error = exc
                time.sleep(self.backoff * (2 ** attempt))
        raise RuntimeError(f"request failed after {self.attempts} attempts: {url}") from last_error

    def fetch_json(self, url: str) -> dict:
        """GET a URL and parse the JSON response body."""
        body = self.retry_request(url)
        return json.loads(body)
''',
    "webclient/src/http.ts": """\
/** Low-level HTTP helpers. */

export class HttpError extends Error {
  constructor(public status: number, message: string) {
    super(message);
    this.name = 'HttpError';
  }
}

export async function request<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, init);
  if (!response.ok) {
    throw new HttpError(response.status, `request failed: ${response.status} ${url}`);
  }
  return (await response.json()) as T;
}

const RETRYABLE = new Set([429, 502, 503, 504]);

/** Like request(), but retries transient failures with exponential backoff. */
export async function fetchWithRetry<T>(url: string, init?: RequestInit, attempts = 3): Promise<T> {
  let lastError: unknown;
  for (let attempt = 0; attempt < attempts; attempt += 1) {
    try {
      return await request<T>(url, init);
    } catch (error) {
      lastError = error;
      const retryable = error instanceof HttpError && RETRYABLE.has(error.status);
      if (!retryable && !(error instanceof TypeError)) {
        throw error;
      }
      await new Promise((resolve) => setTimeout(resolve, 250 * 2 ** attempt));
    }
  }
  throw new Error(`request failed after ${attempts} retries: ${url}`, { cause: lastError });
}
""",
}

_COMMIT_4_FIXES: dict[str, str | None] = {
    "pyserver/validators.py": '''\
"""Input validation for API payloads."""

import re

# Allow plus-addressing (user+tag@host); the previous pattern rejected it.
_EMAIL_RE = re.compile(r"^[A-Za-z0-9._+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")

MAX_TITLE_LENGTH = 200


def validate_title(title: str) -> str:
    """Validate a task title; returns the stripped title or raises ValueError."""
    cleaned = title.strip()
    if not cleaned:
        raise ValueError("title must not be empty")
    if len(cleaned) > MAX_TITLE_LENGTH:
        raise ValueError(f"title longer than {MAX_TITLE_LENGTH} characters")
    return cleaned


def validate_email(email: str) -> str:
    """Validate an email address; returns it lowercased or raises ValueError."""
    cleaned = email.strip().lower()
    if not _EMAIL_RE.match(cleaned):
        raise ValueError(f"invalid email: {email!r}")
    return cleaned
''',
    "pyserver/models/task.py": '''\
"""Task model."""

from dataclasses import dataclass
from enum import Enum


class TaskStatus(str, Enum):
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    DONE = "done"


class TaskPriority(int, Enum):
    LOW = 0
    NORMAL = 1
    HIGH = 2


@dataclass
class Task:
    id: int
    title: str
    status: TaskStatus
    owner_id: int | None
    created_at: str
    priority: TaskPriority = TaskPriority.NORMAL


def task_from_row(row) -> Task:
    """Build a Task from a sqlite3.Row."""
    keys = row.keys() if hasattr(row, "keys") else []
    priority = TaskPriority(row["priority"]) if "priority" in keys else TaskPriority.NORMAL
    return Task(
        id=row["id"],
        title=row["title"],
        status=TaskStatus(row["status"]),
        owner_id=row["owner_id"],
        created_at=row["created_at"],
        priority=priority,
    )
''',
}

_COMMIT_5_SERVICES: dict[str, str | None] = {
    "pyserver/legacy.py": None,  # deleted: superseded by incremental routes
    "pyserver/services/__init__.py": '"""Background services."""\n',
    "pyserver/services/notifications.py": '''\
"""Outbound notifications for task events."""

import json

from pyserver.config import Settings
from pyserver.http_client import HttpClient
from pyserver.models.task import Task


def send_task_notification(settings: Settings, task: Task, event: str) -> bool:
    """POST a webhook when a task changes (created/completed).

    Returns True if the webhook was delivered, False if no webhook is
    configured. Delivery uses HttpClient.retry_request, so transient
    failures are retried with backoff.
    """
    if not settings.webhook_url:
        return False
    client = HttpClient()
    payload = json.dumps({"event": event, "task_id": task.id, "title": task.title})
    client.retry_request(settings.webhook_url, data=payload.encode("utf-8"), method="POST")
    return True
''',
    "pyserver/cache.py": '''\
"""Tiny in-memory TTL cache used for hot lookups (e.g. users by id)."""

import time
from typing import Any, Callable


class MemoCache:
    """Dict-backed cache with per-entry expiry. Not thread-safe."""

    def __init__(self, ttl_seconds: float = 60.0, clock: Callable[[], float] = time.monotonic) -> None:
        self.ttl = ttl_seconds
        self._clock = clock
        self._entries: dict[Any, tuple[float, Any]] = {}

    def get(self, key: Any) -> Any | None:
        entry = self._entries.get(key)
        if entry is None:
            return None
        expires_at, value = entry
        if self._clock() >= expires_at:
            del self._entries[key]
            return None
        return value

    def put(self, key: Any, value: Any) -> None:
        self._entries[key] = (self._clock() + self.ttl, value)

    def clear(self) -> None:
        self._entries.clear()
''',
    "pyserver/routes/users.py": '''\
"""User routes."""

from pyserver.cache import MemoCache
from pyserver.db import Database
from pyserver.models.user import user_from_row
from pyserver.validators import validate_email

_user_cache = MemoCache(ttl_seconds=30.0)


def get_user(db: Database, params: dict) -> dict:
    """Fetch one user by id, with a short-lived cache in front of SQLite."""
    user_id = params["id"]
    cached = _user_cache.get(user_id)
    if cached is not None:
        return cached
    row_list = db.fetch_all("SELECT * FROM users WHERE id = ?", (user_id,))
    if not row_list:
        raise KeyError(f"no such user: {user_id}")
    result = user_from_row(row_list[0]).__dict__
    _user_cache.put(user_id, result)
    return result


def create_user(db: Database, payload: dict) -> dict:
    """Create a user after validating the email address."""
    email = validate_email(payload["email"])
    cursor = db.execute(
        "INSERT INTO users (email, name) VALUES (?, ?)",
        (email, payload.get("name", "")),
    )
    _user_cache.clear()
    return {"id": cursor.lastrowid, "email": email}
''',
    "pyserver/cli.py": '''\
"""Command-line entry point for the taskhub server."""

import argparse

from pyserver.app import run


def main() -> None:
    parser = argparse.ArgumentParser(prog="taskhub")
    parser.add_argument("--config", help="Path to a JSON config file.")
    parser.parse_args()
    run()


if __name__ == "__main__":
    main()
''',
}

_COMMIT_6_AUTH: dict[str, str | None] = {
    "pyserver/auth.py": '''\
"""Password hashing and session tokens (stdlib-only, PBKDF2)."""

import hashlib
import hmac
import os
import secrets

_ITERATIONS = 100_000


def hash_password(password: str, salt: bytes | None = None) -> str:
    """Hash a password with PBKDF2-HMAC-SHA256; returns 'salthex:digesthex'."""
    salt = salt or os.urandom(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, _ITERATIONS)
    return f"{salt.hex()}:{digest.hex()}"


def verify_password(password: str, stored: str) -> bool:
    """Constant-time check of a password against a stored hash."""
    salt_hex, digest_hex = stored.split(":", 1)
    candidate = hashlib.pbkdf2_hmac(
        "sha256", password.encode("utf-8"), bytes.fromhex(salt_hex), _ITERATIONS
    )
    return hmac.compare_digest(candidate.hex(), digest_hex)


def create_session_token() -> str:
    """Generate an opaque, URL-safe session token."""
    return secrets.token_urlsafe(32)
''',
    "pyserver/routes/users.py": '''\
"""User routes."""

from pyserver.auth import create_session_token, hash_password
from pyserver.cache import MemoCache
from pyserver.db import Database
from pyserver.models.user import user_from_row
from pyserver.validators import validate_email

_user_cache = MemoCache(ttl_seconds=30.0)


def get_user(db: Database, params: dict) -> dict:
    """Fetch one user by id, with a short-lived cache in front of SQLite."""
    user_id = params["id"]
    cached = _user_cache.get(user_id)
    if cached is not None:
        return cached
    row_list = db.fetch_all("SELECT * FROM users WHERE id = ?", (user_id,))
    if not row_list:
        raise KeyError(f"no such user: {user_id}")
    result = user_from_row(row_list[0]).__dict__
    _user_cache.put(user_id, result)
    return result


def create_user(db: Database, payload: dict) -> dict:
    """Create a user (hashing any provided password) and start a session."""
    email = validate_email(payload["email"])
    password_hash = hash_password(payload["password"]) if payload.get("password") else None
    cursor = db.execute(
        "INSERT INTO users (email, name) VALUES (?, ?)",
        (email, payload.get("name", "")),
    )
    _user_cache.clear()
    result = {"id": cursor.lastrowid, "email": email, "session": create_session_token()}
    if password_hash is not None:
        result["password_hash"] = password_hash
    return result
''',
    "webclient/src/auth.ts": """\
/** Client-side auth: token storage, login, logout. */

import { fetchWithRetry } from './http';

const TOKEN_KEY = 'taskhub.token';

export function storeToken(token: string): void {
  window.localStorage.setItem(TOKEN_KEY, token);
}

export function getToken(): string | null {
  return window.localStorage.getItem(TOKEN_KEY);
}

export function clearToken(): void {
  window.localStorage.removeItem(TOKEN_KEY);
}

export async function login(email: string, password: string): Promise<void> {
  const result = await fetchWithRetry<{ token: string }>('/api/login', {
    method: 'POST',
    body: JSON.stringify({ email, password }),
  });
  storeToken(result.token);
}
""",
}

_COMMIT_7_JS_TOOLING: dict[str, str | None] = {
    "webclient/scripts/export_tasks.js": """\
// Nightly export of completed tasks to TSV (run with: node scripts/export_tasks.js).

'use strict';

const DEFAULT_LIMIT = 500;

function formatTaskRow(task) {
  const status = task.completedAt ? 'done' : 'open';
  const title = task.title.replace(/\\t/g, ' ');
  return [task.id, status, title].join('\\t');
}

class TaskExporter {
  constructor(baseUrl, limit = DEFAULT_LIMIT) {
    this.baseUrl = baseUrl;
    this.limit = limit;
  }

  async fetchCompleted() {
    const res = await fetch(`${this.baseUrl}/tasks?status=done&limit=${this.limit}`);
    if (!res.ok) {
      throw new Error(`export failed: HTTP ${res.status}`);
    }
    return res.json();
  }

  async exportTsv(stream) {
    const tasks = await this.fetchCompleted();
    for (const task of tasks) {
      stream.write(formatTaskRow(task) + '\\n');
    }
    return tasks.length;
  }
}

module.exports = { TaskExporter, formatTaskRow, DEFAULT_LIMIT };

if (require.main === module) {
  const exporter = new TaskExporter(process.env.TASKHUB_URL || 'http://127.0.0.1:8080');
  exporter
    .exportTsv(process.stdout)
    .then((count) => process.stderr.write(`exported ${count} tasks\\n`))
    .catch((err) => {
      process.stderr.write(String(err) + '\\n');
      process.exit(1);
    });
}
""",
}



# Commit 8 (fixture v3, Phase A go-support): a small Go export service.
# APPEND-ONLY: earlier commits and their SHAs are untouched (D14 pattern).
_COMMIT_8_GO_SERVICE: dict[str, str | None] = {
    "go.mod": """\
module example.com/taskhub

go 1.22
""",
    "goexport/archive.go": """\
// Package goexport batches completed task rows and hands them to a sink.
package goexport

import "strings"

const MaxBatch = 16

// Archive accumulates rows until MaxBatch, then emits them as one blob.
type Archive struct {
\tentries []string
\tsink    Sink
}

func NewArchive(sink Sink) *Archive {
\treturn &Archive{sink: sink}
}

// Add stores a row; when the batch is full it emits automatically.
func (a *Archive) Add(row string) error {
\ta.entries = append(a.entries, row)
\tif len(a.entries) >= MaxBatch {
\t\treturn a.Flush()
\t}
\treturn nil
}

// Flush emits every stored row as a single compacted blob.
func (a *Archive) Flush() error {
\tif len(a.entries) == 0 {
\t\treturn nil
\t}
\tblob := CompactRows(a.entries)
\ta.entries = a.entries[:0]
\treturn a.sink.Deliver(blob)
}

// Size reports the number of rows waiting in the batch.
func (a *Archive) Size() int {
\treturn len(a.entries)
}

var _ = strings.TrimSpace // keep the import honest for the fixture
""",
    "goexport/sink.go": """\
package goexport

import "fmt"

// Sink receives one compacted blob per emission.
type Sink interface {
\tDeliver(blob string) error
}

// PrintSink is the default Sink: it prints blobs to stdout.
type PrintSink struct {
\tprefix string
}

func NewPrintSink(prefix string) *PrintSink {
\treturn &PrintSink{prefix: prefix}
}

func (p *PrintSink) Deliver(blob string) error {
\t_, err := fmt.Println(p.prefix + blob)
\treturn err
}
""",
    "goexport/compact.go": """\
package goexport

import "strings"

// CompactRows joins rows into one newline-separated blob, dropping blanks.
func CompactRows(rows []string) string {
\tkept := make([]string, 0, len(rows))
\tfor _, row := range rows {
\t\tif strings.TrimSpace(row) != "" {
\t\t\tkept = append(kept, row)
\t\t}
\t}
\treturn strings.Join(kept, "\\n")
}
""",
    "gorunner/main.go": """\
// Command gorunner drains the task export queue through goexport.
package main

import (
\tax "example.com/taskhub/goexport"
)

func drain(rows []string) error {
\tsink := ax.NewPrintSink("export: ")
\tvar spool ax.Archive = *ax.NewArchive(sink)
\tfor _, row := range rows {
\t\tif err := spool.Add(row); err != nil {
\t\t\treturn err
\t\t}
\t}
\treturn spool.Flush()
}

func main() {
\tif err := drain([]string{"t1\\tdone", "t2\\tdone"}); err != nil {
\t\tpanic(err)
\t}
}
""",
}


COMMITS: list[tuple[str, dict[str, str | None]]] = [
    ("feat: python server core (models, db, routes, validators)", _COMMIT_1_PY_CORE),
    ("feat: typescript web client (api, store, components)", _COMMIT_2_TS_FRONTEND),
    ("feat: retry logic for outbound and client http requests", _COMMIT_3_RETRY),
    ("fix: allow plus-addressed emails; add task priority", _COMMIT_4_FIXES),
    ("feat: webhook notifications, user cache, cli; drop legacy sync", _COMMIT_5_SERVICES),
    ("feat: password hashing and session tokens", _COMMIT_6_AUTH),
    ("chore: nightly task export script (node)", _COMMIT_7_JS_TOOLING),
    ("feat: go export service (archive batching, sinks, runner)", _COMMIT_8_GO_SERVICE),
]


def _git(repo: Path, *args: str, day: int) -> None:
    date = _BASE_DATE.format(day=day)
    env = dict(
        os.environ,
        GIT_AUTHOR_NAME=_AUTHOR_NAME,
        GIT_AUTHOR_EMAIL=_AUTHOR_EMAIL,
        GIT_COMMITTER_NAME=_AUTHOR_NAME,
        GIT_COMMITTER_EMAIL=_AUTHOR_EMAIL,
        GIT_AUTHOR_DATE=date,
        GIT_COMMITTER_DATE=date,
        HOME=str(repo),  # ignore user-level git config for determinism
        GIT_CONFIG_NOSYSTEM="1",
    )
    subprocess.run(["git", *args], cwd=repo, env=env, check=True, capture_output=True)


def build(dest: Path) -> Path:
    """Build the fixture repo at ``dest`` (removed first if it exists)."""
    dest = dest.resolve()
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)

    _git(dest, "init", "--quiet", "--initial-branch=main", day=1)
    _git(dest, "config", "commit.gpgsign", "false", day=1)

    for day, (message, files) in enumerate(COMMITS, start=1):
        for rel_path, content in files.items():
            target = dest / rel_path
            if content is None:
                _git(dest, "rm", "--quiet", rel_path, day=day)
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8", newline="\n")
            _git(dest, "add", rel_path, day=day)
        _git(dest, "commit", "--quiet", "-m", message, day=day)

    # marker lives inside .git so the fixture's working tree stays clean
    (dest / ".git" / _VERSION_MARKER).write_text(str(FIXTURE_VERSION), encoding="utf-8")
    return dest


def main() -> int:
    default_dest = Path(__file__).parent / FIXTURE_DIRNAME
    dest = Path(sys.argv[1]) if len(sys.argv) > 1 else default_dest
    built = build(dest)
    head = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=built, check=True, capture_output=True, text=True
    ).stdout.strip()
    print(f"miniproject fixture built at {built} (HEAD {head[:12]})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
